# ==============================================================================
# Global SSD & VM Power Saving Configuration (시스템 전역 설정)
# ==============================================================================
# 디스크(SSD) 깨움 주기 지연: 15초 -> 60초
vm.dirty_writeback_centisecs = 6000
vm.dirty_expire_centisecs = 12000
vm.laptop_mode = 5
