# /etc/modprobe.d/iwlwifi.conf
# iwlwifi dynamic loading removal hook
remove iwlwifi \
(/sbin/lsmod | grep -o -e ^iwlmvm -e ^iwldvm -e ^iwlwifi | xargs /sbin/rmmod) \
&& /sbin/modprobe -r mac80211

# Intel Wi-Fi power saving optimization
options iwlwifi power_save=1 power_level=5
